{{- if and .Values.grafana.enabled .Values.grafana.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-grafana-user
  labels:
{{ include "kube-prometheus-stack.labels" $ | indent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-user: {{ .Values.grafana.sealedSecret.adminUser }}
    admin-password: {{ .Values.grafana.sealedSecret.adminPassword }}
  template:
    type: Opaque
{{ end }}
