{{- if and .Values.thanosRuler.enabled .Values.thanosRuler.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "kube-prometheus-stack.thanosRuler.name" . }}-objstore
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ include "kube-prometheus-stack.thanosRuler.name" . }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    objstore: {{ .Values.thanosRuler.sealedSecret.objstore }}
  template:
    type: Opaque
{{ end }}
