apiVersion: v1
kind: Secret
metadata:
  annotations:
    addons_repo_basepath: ""
    addons_repo_path: appsets
    addons_repo_revision: HEAD
    addons_repo_url: https://git.example.com/ops/argocd.git
    cluster_name: in-cluster
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster_name: in-cluster
    enable_argocd: "true"
    enable_ingress_nginx: "true"
    enable_sealed_secrets: "true"
  name: cluster-kubernetes.default.svc
  namespace: argocd
type: Opaque
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
