---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-argocd-configs
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonRepoPath: configs
          addonNamespace: argocd
        selector:
          matchExpressions:
            - key: enable_argocd
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{name}}-argo-cd-configs
    spec:
      project: default
      sources:
        - path: '{{values.addonRepoPath}}'
          repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
      destination:
        namespace: '{{values.addonNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated:
          prune: false
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
