---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: argo-cd
          addonChartVersion: 7.5.0
          addonChartRepositoryNamespace: argocd
          addonChartRepository: https://argoproj.github.io/argo-helm
        selector:
          matchExpressions:
            - key: enable_argocd
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: argocd
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}environments/default/{{values.addonChart}}/values.yaml
              - $values/{{metadata.annotations.addons_repo_basepath}}environments/clusters/{{name}}/{{values.addonChart}}/values.yaml
      destination:
        namespace: '{{values.addonChartRepositoryNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
